let cart=JSON.parse(localStorage.getItem('dx-cart')||'[]'), wish=JSON.parse(localStorage.getItem('dx-wish')||'[]');let current='All';
const $=s=>document.querySelector(s), money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v);
function save(){localStorage.setItem('dx-cart',JSON.stringify(cart));localStorage.setItem('dx-wish',JSON.stringify(wish));counts();}
function counts(){$('#cartCount').textContent=cart.reduce((a,x)=>a+x.qty,0);$('#wishCount').textContent=wish.length;}
function toast(t){let x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>x.classList.remove('show'),1800)}
function filters(active='All'){$('#filters').innerHTML=CATS.map(c=>`<button class="filter ${c===active?'active':''}" data-filter="${c}">${c}</button>`).join('');document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>render(b.dataset.filter,$('#searchInput').value));}
function card(p){let on=wish.includes(p.id);return `<article class="card"><button class="wish ${on?'on':''}" data-wish="${p.id}">${on?'♥':'♡'}</button><button class="quick" data-quick="${p.id}">Quick view</button><div class="card-img"><img src="assets/images/${p.img}.jpg" alt="${p.name}" loading="lazy"><span class="badge">${p.badge}</span></div><div class="card-body"><small>${p.category}</small><h3>${p.name}</h3><p>${p.desc}</p><div class="bottom"><span class="price">${money(p.price)}</span><button class="add" data-add="${p.id}">Add to cart</button></div></div></article>`}
function render(active='All',q=''){current=active;filters(active);let list=PRODUCTS.filter(p=>(active==='All'||p.category===active)&&(p.name+' '+p.category+' '+p.desc).toLowerCase().includes(q.toLowerCase()));let s=$('#sort').value;if(s==='low')list.sort((a,b)=>a.price-b.price);if(s==='high')list.sort((a,b)=>b.price-a.price);if(s==='az')list.sort((a,b)=>a.name.localeCompare(b.name));$('#products').innerHTML=list.length?list.map(card).join(''):'<div class="empty">No products found.</div>';bind();}
function bind(){document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(+b.dataset.add));document.querySelectorAll('[data-wish]').forEach(b=>b.onclick=()=>toggleWish(+b.dataset.wish));document.querySelectorAll('[data-quick]').forEach(b=>b.onclick=()=>quick(+b.dataset.quick));}
function add(id){let x=cart.find(a=>a.id===id);if(x)x.qty++;else cart.push({id,qty:1});save();toast('Added to cart');open('drawer');drawCart();}
function toggleWish(id){wish=wish.includes(id)?wish.filter(x=>x!==id):[...wish,id];save();render(current,$('#searchInput').value);drawWish();}
function drawCart(){let el=$('#cartItems');if(!cart.length){el.innerHTML='<div class="empty">Your cart is empty.</div>';$('#subtotal').textContent='$0.00';return}let total=0;el.innerHTML=cart.map(i=>{let p=PRODUCTS.find(x=>x.id===i.id);total+=p.price*i.qty;return `<div class="drawer-item"><img src="assets/images/${p.img}.jpg"><div><b>${p.name}</b><small>${money(p.price)}</small><div class="qty"><button onclick="qty(${p.id},-1)">−</button><span>${i.qty}</span><button onclick="qty(${p.id},1)">+</button><button onclick="removeItem(${p.id})">Remove</button></div></div></div>`}).join('');$('#subtotal').textContent=money(total)}
function qty(id,d){let x=cart.find(a=>a.id===id);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(a=>a.id!==id);save();drawCart();}
function removeItem(id){cart=cart.filter(a=>a.id!==id);save();drawCart();}
function drawWish(){let el=$('#wishItems'),items=PRODUCTS.filter(p=>wish.includes(p.id));el.innerHTML=items.length?items.map(p=>`<div class="drawer-item"><img src="assets/images/${p.img}.jpg"><div><b>${p.name}</b><small>${money(p.price)}</small><button class="add" onclick="add(${p.id})">Add to cart</button></div></div>`).join(''):'<div class="empty">Your wishlist is empty.</div>';}
function quick(id){let p=PRODUCTS.find(x=>x.id===id);$('#modalContent').innerHTML=`<div class="modal-product"><img src="assets/images/${p.img}.jpg" alt="${p.name}"><div><span class="kicker">${p.category}</span><h2>${p.name}</h2><p>${p.desc}</p><div class="modal-price">${money(p.price)}</div><button class="btn red" onclick="add(${p.id});closeAll()">Add to cart</button></div></div>`;$('#modal').classList.add('open');}
function open(id){$('#'+id).classList.add('open');$('#overlay').classList.add('open')}function closeAll(){document.querySelectorAll('.drawer,.modal,.overlay').forEach(x=>x.classList.remove('open'))}
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeAll);$('#overlay').onclick=closeAll;$('#cartBtn').onclick=()=>{drawCart();open('drawer')};$('#wishBtn').onclick=()=>{drawWish();open('wishDrawer')};$('#searchBtn').onclick=()=>{$('#search').classList.toggle('open');$('#searchInput').focus()};$('#searchInput').oninput=e=>render(current,e.target.value);$('#sort').onchange=()=>render(current,$('#searchInput').value);
document.querySelectorAll('[data-cat]').forEach(a=>a.onclick=()=>{render(a.dataset.cat,'');setTimeout(()=>document.querySelector('#shop').scrollIntoView({behavior:'smooth'}),20)});
$('#checkout').onclick=()=>toast('Demo checkout — connect your payment provider before launch.');$('#newsletter').onsubmit=e=>{e.preventDefault();$('#newsMsg').textContent='You are on the DIAMONDX list.';e.target.reset();toast('Welcome to the clubhouse!')};$('#supportForm').onsubmit=e=>{e.preventDefault();$('#supportMsg').textContent='Thanks — your request is ready to connect to your helpdesk.';e.target.reset();toast('Support request received')};counts();render();
